// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6HmDsmtK3JLJjT13MXd48geYb202Z3gk',
    appId: '1:928895619267:web:facb513cffae7292b91276',
    messagingSenderId: '928895619267',
    projectId: 'cravy-9a55b',
    authDomain: 'cravy-9a55b.firebaseapp.com',
    storageBucket: 'cravy-9a55b.firebasestorage.app',
    measurementId: 'G-5G01V3L6YG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBf4rQAE09ew3aQHkccsRTFsA07mSdK23o',
    appId: '1:928895619267:android:961df91692dc9cafb91276',
    messagingSenderId: '928895619267',
    projectId: 'cravy-9a55b',
    storageBucket: 'cravy-9a55b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYwGIsbsBLO4Sqk9lGZIOtZ2-wrwwnsb8',
    appId: '1:928895619267:ios:8b8951c587d25336b91276',
    messagingSenderId: '928895619267',
    projectId: 'cravy-9a55b',
    storageBucket: 'cravy-9a55b.firebasestorage.app',
    androidClientId: '928895619267-l1npdehkl3ldvduosf3t8fokm5hcjqjv.apps.googleusercontent.com',
    iosClientId: '928895619267-fbve1fb4kl0m6acktjq6hdejogekigik.apps.googleusercontent.com',
    iosBundleId: 'com.example.cravy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYwGIsbsBLO4Sqk9lGZIOtZ2-wrwwnsb8',
    appId: '1:928895619267:ios:8b8951c587d25336b91276',
    messagingSenderId: '928895619267',
    projectId: 'cravy-9a55b',
    storageBucket: 'cravy-9a55b.firebasestorage.app',
    androidClientId: '928895619267-l1npdehkl3ldvduosf3t8fokm5hcjqjv.apps.googleusercontent.com',
    iosClientId: '928895619267-fbve1fb4kl0m6acktjq6hdejogekigik.apps.googleusercontent.com',
    iosBundleId: 'com.example.cravy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB6HmDsmtK3JLJjT13MXd48geYb202Z3gk',
    appId: '1:928895619267:web:921e700e83b11915b91276',
    messagingSenderId: '928895619267',
    projectId: 'cravy-9a55b',
    authDomain: 'cravy-9a55b.firebaseapp.com',
    storageBucket: 'cravy-9a55b.firebasestorage.app',
    measurementId: 'G-D65YT3EK2Y',
  );
}
